"""Writer agent: compiles everything into a markdown investment memo."""

from __future__ import annotations

import logging
from datetime import datetime

from src.agents.state import AgentState
from src.models.memo import RiskLevel

logger = logging.getLogger(__name__)


def _format_value(val: float | None, fmt: str = ",.2f", prefix: str = "", suffix: str = "") -> str:
    if val is None:
        return "N/A"
    return f"{prefix}{val:{fmt}}{suffix}"


def _format_large(val: float | None) -> str:
    if val is None:
        return "N/A"
    if abs(val) >= 1e12:
        return f"${val / 1e12:,.2f}T"
    if abs(val) >= 1e9:
        return f"${val / 1e9:,.2f}B"
    if abs(val) >= 1e6:
        return f"${val / 1e6:,.2f}M"
    return f"${val:,.0f}"


async def writer_node(state: AgentState) -> AgentState:
    """Compile analysis results into a structured markdown report."""
    if "error" in state and state["error"]:
        error_report = f"""# Investment Memo — {state.get('ticker', 'UNKNOWN')}

> **Status:** FAILED
> **Error:** {state['error']}
> **Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
"""
        return {**state, "report_md": error_report}

    financials = state.get("financials")
    risk_flags = state.get("risk_flags", [])
    recommendation = state.get("recommendation", "REVIEW")
    confidence = state.get("confidence", 0.0)

    # Risk flags table
    risk_rows = ""
    if risk_flags:
        for f in sorted(risk_flags, key=lambda x: ["LOW", "MEDIUM", "HIGH", "CRITICAL"].index(x.level)):
            emoji = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🟠", "CRITICAL": "🔴"}.get(
                f.level, "⚪"
            )
            metric_info = f" (`{f.metric}` = {f.value})" if f.metric else ""
            risk_rows += f"| {emoji} {f.level} | {f.category} | {f.description}{metric_info} |\n"
    else:
        risk_rows = "| — | — | No significant risks identified |\n"

    # News section
    news = state.get("news", [])
    news_section = ""
    if news:
        news_section = "\n".join(f"- [{n.title}]({n.link})" if n.link else f"- {n.title}" for n in news[:8])
    else:
        news_section = "_No recent news available_"

    ticker = state.get("ticker", "???")
    name = financials.name if financials else ticker

    report = f"""# Investment Memo — {name} ({ticker})

> **Recommendation:** **{recommendation}**
> **Confidence:** {confidence:.0%}
> **Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

---

## Summary

{state.get('summary', 'N/A')}

## Investment Thesis

{state.get('thesis', 'N/A')}

## Key Financial Metrics

| Metric | Value |
|--------|-------|
| Market Cap | {_format_large(financials.market_cap) if financials else 'N/A'} |
| P/E Ratio | {_format_value(financials.pe_ratio if financials else None)} |
| Forward P/E | {_format_value(financials.forward_pe if financials else None)} |
| Price/Book | {_format_value(financials.price_to_book if financials else None)} |
| Debt/Equity | {_format_value(financials.debt_to_equity if financials else None)} |
| Revenue Growth | {_format_value(financials.revenue_growth if financials else None, '.1%')} |
| Profit Margin | {_format_value(financials.profit_margin if financials else None, '.1%')} |
| ROE | {_format_value(financials.roe if financials else None, '.1%')} |
| Current Ratio | {_format_value(financials.current_ratio if financials else None)} |
| Beta | {_format_value(financials.beta if financials else None)} |
| Free Cash Flow | {_format_large(financials.free_cash_flow) if financials else 'N/A'} |
| 52-wk Range | {_format_value(financials.fifty_two_week_low if financials else None, '.2f', '$')} — {_format_value(financials.fifty_two_week_high if financials else None, '.2f', '$')} |
| Current Price | {_format_value(financials.current_price if financials else None, '.2f', '$')} |

## Risk Assessment

| Level | Category | Description |
|-------|----------|-------------|
{risk_rows}
**Total flags:** {len(risk_flags)} | \
**Critical:** {sum(1 for f in risk_flags if f.level == RiskLevel.CRITICAL)} | \
**High:** {sum(1 for f in risk_flags if f.level == RiskLevel.HIGH)}

## Recent News

{news_section}

---

_This memo was generated by Investment Memo Agent (LangGraph multi-agent pipeline)._
"""

    return {**state, "report_md": report.strip()}
